---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/dishes":
    get:
      summary: get all dished
      tags:
      - Dishes
      consumes:
      - application/json
      - application/xml
      responses:
        '200':
          description: get all dishes
    post:
      summary: Creates a dishes
      tags:
      - Dishes
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: dish
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
      responses:
        '201':
          description: dishes created
  "/api/v1/dishes/{id}":
    get:
      summary: get dishes
      tags:
      - Dishes
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: get dishes
    put:
      summary: Update a dishes
      tags:
      - Dishes
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      - name: dish
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
      responses:
        '200':
          description: dishes updated
    delete:
      summary: remove dishes
      tags:
      - Dishes
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '204':
          description: authenticated
